config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'products#index'

  resources :products
  resources :carts
  resources :line_items

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  enum state: [:created, :completed]

  belongs_to :user
  has_many :line_items
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :line_items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :carts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def create
    cart = current_user.carts.where(state: 'created').first_or_create
    line_item = cart.line_items.where(product_id: params[:product]).first_or_create
    increase_quantity(line_item)
    line_item.save
    redirect_to products_path
  end

  def update
    cart = current_user.carts.find(params[:id])
    cart.update(state: 'completed')
    redirect_to products_path
  end

  private

  def increase_quantity(line_item)
    line_item.quantity += 1
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to products_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
    @cart = current_user.carts.where(state: 'created').last
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def show
  end

  def create
    @product = Product.new(product_params)
    @product.save ? (redirect_to products_path) : (render 'new')
  end

  def update
    if @product.update(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <p><%= current_user.email if user_signed_in? %><p/>
      <% if user_signed_in? %>
        <%=link_to "See all products", products_path %>
        <%=link_to "Edit profile", edit_user_registration_path %>
        <%=link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%=link_to "Sign In", new_user_session_path %>
        <%=link_to "Sign Up", new_user_registration_path %>
      <% end %>
  </header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for product do |p| %>
  <%= p.label :name %><br />
	<%= p.text_field :name %><br />
  <%= p.label :price %><br />
	<%= p.text_field :price %><br />
  <%= p.label :image %><br />
  <%= p.file_field :image %>
	<%= p.submit (product.new_record? ? 'Create product' : 'Update product') %>
<% end %>

app/views/products/edit.html.erb
<p>Edit product</p>
<%= render partial: 'form', locals: { product: @product } %>
<p><%= link_to "Back", products_path %></p>

app/views/products/index.html.erb
<p>Total number of products:</p>
<p><%= @products.count %></p>
<%= link_to 'New product', new_product_path %>
<br /><br />
<table style='width:40%;text-align:left'>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Price</th>
    <th>Image</th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= image_tag product.image.url(:thumb) %></td>
      <td><%= link_to 'Add to Cart', carts_path(product: product), method: :post %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Delete', product_path(product), method: :delete %></td>
    </tr>
  <% end %>
</table>
<br />
<p><b>Item in Cart (id):</b></p>
<% if @cart %>
<p><b><%= @cart.line_items.count %></b></p>
  <% @cart.line_items.each do |line_item| %>
    <p><%= line_item.product.name %></p>
    <%= image_tag line_item.product.image.url(:thumb) if line_item.product.image.present? %></p>
    <p><%= line_item.quantity %></p>
    <p><%= link_to 'Remove item from cart', line_item_path(line_item), method: :delete %></p>
  <% end %>
<% else %>
  <p>Cart is empty!</p>
<% end %>
<br />
<p><%= (link_to 'Complete order', cart_path(@cart), method: :put) if @cart %></p>
<br />

app/views/products/new.html.erb
<p>Add new product</p>
<%= render partial: 'form', locals: { product: @product } %>
<p><%= link_to "Back", products_path %></p>

app/views/products/show.html.erb
<p>Id: <%= @product.id%></p>
<p>Name: <%= @product.name%></p>
<p>Price: <%= @product.price%></p>
<%= image_tag @product.image.url(:medium) %>
<p><%= link_to "Back", products_path %></p>